# Generated by Django 4.2.7 on 2024-04-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDataModel',
        ),
    ]
