# Generated by Django 5.0.4 on 2024-05-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_delete_admindatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='posters/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
