# Generated by Django 5.0.4 on 2024-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtsmodel',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
