# Generated by Django 5.0.4 on 2024-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonationmodel',
            name='donation_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
