# Generated by Django 5.0.4 on 2024-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_userdonationmodel_donation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonationmodel',
            name='hospital_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdonationmodel',
            name='hospital_patient_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
