# Generated by Django 5.0.4 on 2024-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_userdonationmodel_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonationmodel',
            name='donation_file',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='userdonationmodel',
            name='hospital_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
