# Generated by Django 5.0.4 on 2025-11-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0005_alter_districtsmodel_state_id"),
        ("UserApp", "0006_userdonationmodel_donation_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AdminApp.statemodel",
            ),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
