# Generated by Django 5.0.4 on 2025-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0007_userprofilemodel_full_name_userprofilemodel_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilemodel",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="profile"),
        ),
    ]
