# Generated by Django 5.0.4 on 2025-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0008_alter_userprofilemodel_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdonationmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userpostmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
