# Generated by Django 5.0.4 on 2025-11-23 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0005_alter_districtsmodel_state_id"),
        ("UserApp", "0009_userdonationmodel_slug_userpostmodel_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdonationmodel",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="AdminApp.donationcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="comments",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="contact_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="donation_file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="donation_user_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="hospital_name",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="hospital_patient_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="AdminApp.districtsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="status",
            field=models.CharField(blank=True, default="Pending", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="title",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="userdonationmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
