# Generated by Django 5.0.4 on 2025-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0010_alter_userdonationmodel_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="e.g. Queens, New York, NY",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="notify_donations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="notify_messages",
            field=models.BooleanField(default=True),
        ),
    ]
